### ISSUE TITLE
不太理解为什么要改造源代码来传递id?

### ISSUE THREAD

**Issue by wymli** [didi/sharingan#11]
关于上下游流量inbound/outbound的对应匹配:
    这应该是框架做的事情,框架应该维护一个traceid,跟着流量在全链路传播

关于工作委托:
    在业务层,应该通过context来传递信息吧,而不是修改源码,把数据存在源码未导出的结构体.

请问使用一个context来传递相关的threadlocal信息有什么局限吗?

**Comment by yj20060714** [comment]
1）sharingan工具不局限于框架，任何框架都可以用，这是工具的一个特色
2）sharingan录制和回放的层级，是底层TCP层，不是框架层，可以详见wiki
